version: '3'
services:
  server:
    image: node:latest
    working_dir: /server
    ports: 
      - 3000:3000
    environment: 
      - PGUSER=teleblah
      - PGHOST=db
      - PGPASSWORD=blogsdbpass
      - PGDATABASE=blogsdb
      - PGPORT=5432
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./
        target: /server
    command: bash -c "npm install && npm start"

  db:
    image: postgres:latest
    ports:
      - 35432:5432
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./db/seeds.sql:/docker-entrypoint-initdb.d/seeds.sql:ro"
    environment: 
      - POSTGRES_DB=blogsdb
      - POSTGRES_USER=teleblah
      - POSTGRES_PASSWORD=blogsdbpass
volumes:
  dbdata: